/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2017 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package firebase.firestore;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import com.google.firebase.firestore.FirebaseFirestore;

@Kroll.module(name = "Tifirebase", id = "firebase.firestore")
public class TifirestoreModule extends KrollModule {

	// Standard Debugging variables
	private static final String LCAT = "TiFirestore";
	private static final boolean DBG = TiConfig.LOGD;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	public FirebaseFirestore db ;
	public TifirestoreModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		Log.d(LCAT, "inside onAppCreate");
	}

	// Methods
	@Kroll.method
	public void connect() {
		if (db ==null)
		db = FirebaseFirestore.getInstance();
		
	}
	@Kroll.method
	public void setLoggingEnabled(boolean enabled) {
		FirebaseFirestore.setLoggingEnabled(enabled);
	}
}
